# TUGAS
## Pengenalan Array dengan Numpy

Kelompok 4
1. Adis Koswara
2. Fauzaan alif Syafiindra
3. Mohamad ridho Gusdanaputra
4. Restu kurniawan Sumarna
5. Yusuf Radana




In [1]:
# import libraries
import numpy as np
# buat matriks (arr) shape 2x3 dengan tipe data integer 64
# [[ 1  2  3 ]
#  [ 5  6  7 ]]
arr = np.array([[1, 2, 3], [5, 6, 7]], dtype=np.int64)
# print arr
print("Matrix (arr):\n", arr)
# print shape arr
print("Shape of arr:", arr.shape)
# print tipe data arr
print("Data type of arr:", arr.dtype)

Matrix (arr):
 [[1 2 3]
 [5 6 7]]
Shape of arr: (2, 3)
Data type of arr: int64


In [2]:
# buat matriks (arr_rdm) shape 2x3 dengan tipe data integer 64
# nilai elemennya random
arr_rdm = np.random.randint(1, 75, size=(2, 3), dtype=np.int64)
# print arr_rdm
print("Random Matrix (arr_rdm):\n", arr_rdm)
# print shape arr_rdm
print("Shape of arr_rdm:", arr_rdm.shape)
# print tipe data arr_rdm
print("Data type of arr_rdm:", arr_rdm.dtype)

Random Matrix (arr_rdm):
 [[ 7 13  5]
 [34  9 41]]
Shape of arr_rdm: (2, 3)
Data type of arr_rdm: int64


# Aritmatika Dasar dengan Numpy

In [6]:
arr = np.array([[4, 2, 5], [1, 8, 2]], dtype=np.int64)
arr_rdm = np.random.randint(1, 75, size=(2, 3), dtype=np.int64)
# operasi penjumlahan arr dan arr_rdm
sum_result = arr + arr_rdm
# operasi pengurangan arr dan arr_rdm
subtraction_result = arr - arr_rdm
# operasi perpangkatan dua arr_rdm
power_result = arr_rdm ** 2
# operasi perkalian elemen arr dan arr_rdm
elementwise_multiplication_result = arr * arr_rdm
# Transpose matriks arr_rdm
arr_rdm_transposed = np.transpose(arr_rdm)
# operasi perkalian matriks arr dan arr_rdm
matrix_multiplication_result = np.dot(arr, arr_rdm_transposed)
# Menampilkan hasil
print("Hasil Penjumlahan:\n", sum_result)
print("Hasil Pengurangan:\n", subtraction_result)
print("Hasil Perpangkatan Dua:\n", power_result)
print("Hasil Perkalian Elemen:\n", elementwise_multiplication_result)
print("Transpose arr_rdm:\n", arr_rdm_transposed)
print("Hasil Perkalian Matriks:\n", matrix_multiplication_result)

Hasil Penjumlahan:
 [[21 13 66]
 [50 71 10]]
Hasil Pengurangan:
 [[-13  -9 -56]
 [-48 -55  -6]]
Hasil Perpangkatan Dua:
 [[ 289  121 3721]
 [2401 3969   64]]
Hasil Perkalian Elemen:
 [[ 68  22 305]
 [ 49 504  16]]
Transpose arr_rdm:
 [[17 49]
 [11 63]
 [61  8]]
Hasil Perkalian Matriks:
 [[395 362]
 [227 569]]


In [7]:
arr = np.array([[1, 2, 3], [5, 6, 7]], dtype=np.int64)
# print nilai rata-rata arr
rata_rata_arr = np.mean(arr)
# print nilai rata-rata per baris arr
rata_rata_per_baris = np.mean(arr, axis=1)
# print total nilai seluruh elemen matriks arr
total_nilai = np.sum(arr)
# print nilai maximal per kolom matriks arr
maksimal_per_kolom = np.max(arr, axis=0)
# Menampilkan hasil
print("Nilai Rata-rata arr:", rata_rata_arr)
print("Nilai Rata-rata per Baris arr:", rata_rata_per_baris)
print("Total Nilai Seluruh Elemen Matriks arr:", total_nilai)
print("Nilai Maksimal per Kolom Matriks arr:", maksimal_per_kolom)

Nilai Rata-rata arr: 4.0
Nilai Rata-rata per Baris arr: [2. 6.]
Total Nilai Seluruh Elemen Matriks arr: 24
Nilai Maksimal per Kolom Matriks arr: [5 6 7]


# Fitur pada Numpy

In [8]:
arrg = np.arange(1, 21)
# buat array arrg dengan nilai range 1-20
arrg = np.arange(1, 21)
# print arrg
print("arrg:", arrg)
# print nilai arrg index 5
print("Nilai arrg index 5:", arrg[5])
# print nilai arrg untuk 3 elemen dari terakhir
print("3 elemen terakhir arrg:", arrg[-3:])
# print nilai arrg 3 sampai 6
print("Nilai arrg dari indeks 3 hingga 6:", arrg[3:7])

arrg: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Nilai arrg index 5: 6
3 elemen terakhir arrg: [18 19 20]
Nilai arrg dari indeks 3 hingga 6: [4 5 6 7]


In [111]:
arr = np.array([[1, 2, 3], [5, 6, 7]], dtype=np.int64)
# print matriks arr
print("Matriks arr:")
print(arr)
# print slice matriks arr dengan output
## [[ 2  3 ]
##  [ 6  7 ]]
slice1 = arr[:, 1:]
print("\nSlice matriks arr (output [[2 3] [6 7]]):")
print(slice1)
# print slice matriks arr dengan output
## [[ 3 ]
##  [ 7 ]]
slice2 = arr[:, 2:]
print("\nSlice matriks arr (output [[3] [7]]):")
print(slice2)

Matriks arr:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Slice matriks arr (output [[2 3] [6 7]]):
[[2 3]
 [5 6]]

Slice matriks arr (output [[3] [7]]):
[[3]
 [6]]


In [50]:

# buat matriks mtx_rdm ukuran 3x4 dengan tipe data integer, isi elemennya random
mtx_rdm = np.random.randint(1, 76, (3, 4), dtype=int)
# print mtx_rdm shape
print("Shape dari mtx_rdm:")
print(mtx_rdm.shape)
# ubah shape mtx_rdm menjadi satu dimensi
mtx_1d = mtx_rdm.flatten()
# Mencetak matriks satu dimensi
print("\nMatriks satu dimensi (flatten):")
print(mtx_1d)
# ubah shape mtx_rdm menjadi 6x2
mtx_reshaped = mtx_rdm.reshape(6, 2)
# Mencetak matriks dengan shape yang sudah diubah
print("\nMatriks dengan shape 6x2:")
print(mtx_reshaped)

Shape dari mtx_rdm:
(3, 4)

Matriks satu dimensi (flatten):
[16 10  5 60  8 59 38 26 30 44 73 50]

Matriks dengan shape 6x2:
[[16 10]
 [ 5 60]
 [ 8 59]
 [38 26]
 [30 44]
 [73 50]]
